function(cmk_get_relative_path OUTPUT_VARIABLE)

    string(LENGTH ${PROJECT_SOURCE_DIR} TOP_DIR_ABS_PTH_LEN)

    math(EXPR TOP_DIR_ABS_PTH_LEN_ADD_ONE "${TOP_DIR_ABS_PTH_LEN} + 1")

    string(SUBSTRING ${CMAKE_CURRENT_SOURCE_DIR} ${TOP_DIR_ABS_PTH_LEN_ADD_ONE} -1 CUR_DIR_REL_PTH)

    set(${OUTPUT_VARIABLE} ${CUR_DIR_REL_PTH} PARENT_SCOPE)

endfunction()
