name: linux

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: cmk - config
      run: cmake -B build

    - name: cmk - install
      run: sudo cmake --install build
