name: windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: cmk - config
      run: cmake -B build

    - name: cmk - install
      run: cmake --install build
